### ISSUE TITLE
Description field no mandatory field

### ISSUE THREAD

**Issue by Batman777** [jweiland-net/yellowpages2#1]
Hello,
is it possible to remove the mandatory field in the description textarea?

**Comment by froemken** [comment]
Hello Batman777. As yellowpages2 is installed as it is, in various places, I can't change that for current community version. This would break many existing installations.

Please refer to this documentation:
http://www.lukasjakob.com/extend-a-typo3-extbase-model-with-custom-field/

I have programmed yellowpages2 on extbase/fluid. So you can override nearly everything with your own extension. Please extend my domain model with your own model and override the field description and change the annotation. Further you have to remove "required" from eval-property in TCA.

Nice greetings

Stefan Frömken
