### ISSUE TITLE
You can’t save a new record as normal user

### ISSUE THREAD

**Issue by hloens** [jweiland-net/yellowpages2#54]
If you save a new record with the bare minimum as input, you get the error message:
![230110_error_save_msg](https://user-images.githubusercontent.com/96468052/211580400-60bcbf61-fcf8-402c-92c5-7a76e982f7f0.png)
and your record is lost.

This doesn't happen if you are logged in as an admin.

**Comment by froemken** [comment]
Ahoi Hauke,

thank you for your help. I have removed "NOT NULL" in ext_tables.php and add a lot of `default = 0` to TCA.
Problem solved in current master.

Stefan
